- name: Deploy
  hosts: all
  tasks:
    - name: Copy Docker Compose files
      copy:
        src: "{{ item }}"
        dest: "{{ deploy_project_path }}/"
      with_fileglob:
        - ./docker-compose.base.yaml

    - name: Copy env files
      copy:
        src: "./etc/envs"
        dest: "{{ deploy_project_path }}/etc/"

    - name: Start docker-compose
      community.docker.docker_compose:
        project_src: "{{ deploy_project_path }}/"
        files:
          - docker-compose.base.yaml

    - name: Start app
      community.docker.docker_container:
        name: day_statistic_backend_app
        image: "{{ app_image_url }}"
        volumes:
          - "{{ deploy_project_path }}/etc/envs/:/etc/envs"
        networks:
          - name: day_statistic_backend_default
        ports:
          - "8080:80" # temporary solution until nginx isn't added
