- name: Deploy
  hosts: all
  tasks:
    - name: Copy Docker Compose files
      copy:
        src: "{{ item }}"
        dest: "{{ deploy_project_path }}"
      with_fileglob:
        - ./docker-compose.base.yaml

    - name: Copy env files
      copy:
        src: "./etc/envs"
        dest: "{{ deploy_project_path }}/etc/"

    - name: Start docker-compose
      community.docker.docker_compose:
        profiles: "with_app"
        project_src: "{{ deploy_project_path }}"
        files:
          - docker-compose.base.yaml

    - name: Start app
      community.docker.docker_container:
        name: app
        image: "{{ app_image_url }}"
        volumes:
          - "{{ deploy_project_path }}/etc/envs/:/etc/envs"
        ports:
          - "8080:80" # temporary solution until nginx isn't added

    - name: Remove unused docker data
      community.docker.docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
