version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.9
    restart: always
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./etc/envs/mongodb.env

volumes:
  mongodb_data:
