version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.9
    restart: always
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./etc/envs/mongodb.env

  redis:
    container_name: redis
    image: redislabs/rejson:2.2.0
    restart: always
    volumes:
      - redis_data:/data
    env_file:
      - ./etc/envs/redis.env

volumes:
  mongodb_data:
  redis_data:
