name: cd
on:
  workflow_dispatch:
    inputs:
      app_image_tag:
        description: Tag of docker image with app
        default: latest
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://206.188.197.52:8080
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Add poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.14

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}

      - name: Override environment files
        run: |
          echo "$MONGODB_ENV" > ./etc/envs/mongodb.env
          echo "$APP_ENV" > ./etc/envs/app.env
        env:
          MONGODB_ENV: ${{ secrets.MONGODB_ENV }}
          APP_ENV: ${{ secrets.APP_ENV }}

      - name: Deploy project
        run: make deploy DEPLOY_HOST="$DEPLOY_HOST" DEPLOY_USER="$DEPLOY_USER" DEPLOY_PROJECT_PATH="$DEPLOY_PROJECT_PATH" APP_IMAGE_URL=ghcr.io/${{ github.repository }}:${{ github.event.inputs.app_image_tag }}
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PROJECT_PATH: ${{ secrets.DEPLOY_PROJECT_PATH }}
