# TODO improve description
name: ci
on: [push, pull_request_target]
jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Add poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.14

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Check by linters
        run: make lint_check


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Add poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.14

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Test
        run: make test


  build:
    needs: [test, lint_check]
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - run: echo ${{ github.actor }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ steps.branch-name.outputs.current_branch }}
